language: python
python:
    - 2.7
install: pip install -r requirements.txt
script: python manage.py celeryd -E -B --loglevel=INFO
script: python manage.py test
before_script: 
  - psql -c 'create database test_csv_manager;' -U postgres
  - psql -c 'CREATE USER csv_manager WITH PASSWORD 'csvmanagerpass;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE test_csv_manager to csv_manager;' -U postgres
after script:
  
